# cloudbuild.yaml
steps:
  # Step 1: Install dependencies AND run script in same container
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing system dependencies..."
        apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0
        
        echo "Upgrading pip..."
        pip install --upgrade pip
        
        echo "Installing Python packages..."
        pip install -r requirements.txt
        
        echo "Running Python script..."
        python3 run.py
        
        echo "Build completed successfully!"
  
  # Step 2: Post-build - list files for verification
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Listing all generated files..."
        ls -R frame_data/
        ls -la result.json 2>/dev/null || echo "result.json not found"
  
  # Step 3: Upload result.json separately
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'upload-videoFrames'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f result.json ]; then
          gsutil cp result.json gs://video-processing123/artifacts/videoFrames/result.json
          echo "Successfully uploaded result.json"
        else
          echo "Warning: result.json not found"
        fi

# Main artifacts - uploaded automatically at build completion
artifacts:
  objects:
    location: 'gs://video-processing123/artifacts/'
    paths:
      - 'frame_data/frames/**'    # Everything under frames/ recursively
      - 'frame_data/predict/**'   # Everything under predict/ recursively
      - 'result.json'             # The main result file

# Options
options:
  logging: CLOUD_LOGGING_ONLY
